[track]
author: Jujucece
nbCheckpoint: 12
[normal]
startAngle: 3.14
startX1: 500
startY1: 645
startX2: 500
startY2: 695
startX3: 450
startY3: 645
startX4: 450
startY4: 695
[reverse]
startAngle: 4.7124
startX1: 106
startY1: 290
startX2: 161
startY2: 267
startX3: 106
startY3: 244
