[track]
author: Jujucece
nbCheckpoint: 11
[normal]
startAngle: 3.14
startX1: 200
startY1: 400
startX2: 200
startY2: 450
startX3: 150
startY3: 400
StartX4: 150
StartY4: 450
[reverse]
startAngle: 4.4
startX1: 625
startY1: 445
startX2: 695
startY2: 405
startX3: 605
startY3: 385
