[track]
author: Jujucece
nbCheckpoint: 6
[normal]
startAngle: 0
startX1: 370
startY1: 725
startX2: 410
startY2: 655
startX3: 450
startY3: 725
[reverse]
startAngle: 3.14
startX1: 265
startY1: 725
startX2: 245
startY2: 655
startX3: 225
startY3: 725
