[track]
Author: Brendan
<<<<<<< HEAD
nbCheckpoint: 7
=======
nbCheckpoint: 11
>>>>>>> 8e1f1c91c673389bedd92d4dc18987de29e57f3e
[normal]
startAngle: 0
startX1: 596
startY1: 101
startX2: 596
startY2: 51
startX3: 646
startY3: 101
startX4: 646
startY4: 51