[track]
author: Jujucece
nbCheckpoint: 14
[normal]
startAngle: 3.14
startX1: 630
startY1: 350
startX2: 580
startY2: 420
startX3: 530
startY3: 350
[reverse]
startAngle: 0
startX1: 690
startY1: 350
startX2: 710
startY2: 420
startX3: 730
startY3: 350
